image: Ubuntu2004

stack: node 21

branches:
  only:
    - main

install:
  - yarn install

build: off

build_script:
  - yarn build

test_script:
  - yarn lint

deploy_script: 
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com 
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
